# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2227d1455d291fa4ab155db2b9df3b04576cccdf2c831aa6f3517813c8f4c92d5d9d78d979853a0936a4555a11a1dc0d860d31eb8d3fd3dd8e2f147c7d59ead7

test:
  secret_key_base: f48a6cde4b43541613055fc9aa6df40f4c9f49eaa0af627ad78a61c98edcf6b6d73dd6615d1fd289be9e70be4a7d5a4dc6a6a3a44e9ff94c7e1ad4b35e1e28af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
